# Generated by Django 4.1.3 on 2023-07-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='background_choice',
            field=models.CharField(choices=[('default', 'Default'), ('color', 'Color'), ('image', 'Image'), ('custom_css', 'Custom CSS')], default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='background_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='background_image_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='custom_css',
            field=models.TextField(blank=True, null=True),
        ),
    ]
