# Generated by Django 4.1.3 on 2023-06-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_category_tag_alter_blogpost_content_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
