# Generated by Django 4.1.3 on 2023-05-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ContactUs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactdata",
            name="contact",
            field=models.BigIntegerField(),
        ),
    ]
