# Generated by Django 4.1.3 on 2023-05-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ContactUs", "0002_alter_contactdata_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactdata",
            name="contact",
            field=models.IntegerField(),
        ),
    ]
