# Generated by Django 4.1.3 on 2023-05-24 21:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MemberDetails",
            new_name="MemberDetail",
        ),
    ]
