# Generated by Django 4.1.3 on 2023-06-14 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberDetail',
        ),
    ]
