# Generated by Django 4.1.3 on 2023-05-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_memberdetail_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberdetail",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
