# Generated by Django 4.1.3 on 2023-06-03 18:47

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_memberdetail_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memberdetail",
            name="id",
        ),
        migrations.AddField(
            model_name="memberdetail",
            name="_id",
            field=djongo.models.fields.ObjectIdField(
                auto_created=True,
                db_column="_id",
                default=3,
                primary_key=True,
                serialize=False,
            ),
            preserve_default=False,
        ),
    ]
