# Generated by Django 4.1.3 on 2023-05-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Email_Notice_App", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailmessage",
            name="html_file",
            field=models.FileField(blank=True, upload_to="html_files/"),
        ),
    ]
